spring:
   application:
      name: service-registry-server
   profiles:
      active: development
    
server:
   port: 8761

   
---
#
# development configuration
#
spring:
   config:
      activate:
         on-profile: development
   
eureka:
   instance:
      hostname: localhost
   server:
      enableSelfPreservation: false
      waitTimeInMsWhenSyncEmpty: 5        
   client:
      fetchRegistry: false
      registerWithEureka: false
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO

      
---
#
# production configuration
#
spring:
   config:
      activate:
         on-profile: production
   
eureka:
   instance:
      hostname: 192.168.0.69
   server:
      enableSelfPreservation: false   # 네트워크 장애났을 때, 서비스 없애는 거 방지
      waitTimeInMsWhenSyncEmpty: 5    # 0.0005초로 바꿈    
   client:
      fetchRegistry: false
      registerWithEureka: false
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB  # 10MB넘어가면 zip으로 만듦
         max-history: 30      # 계속할 수가 없어서, 30개까지 생김
         
   file:
      name: logs/${spring.application.name}.log

   level:
      root: WARN
      me:
         kickscar:
            emaillist:
               exception: ERROR
         